# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#9ccfd8" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#c4a7e7", bold = true, italic = true, underline = true }
find_position = { fg = "#f6c177", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#31748f", bg = "#31748f" }
marker_cut      = { fg = "#eb6f92", bg = "#eb6f92" }
marker_marked   = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_selected = { fg = "#c4a7e7", bg = "#c4a7e7" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#191724", bg = "#31748f" }
count_cut      = { fg = "#191724", bg = "#eb6f92" }
count_selected = { fg = "#191724", bg = "#c4a7e7" }

# Border
border_symbol = "│"
border_style  = { fg = "#6e6a86" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#191724", bg = "#ebbcba", bold = true }
inactive = { fg = "#ebbcba", bg = "#403d52" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#191724", bg = "#ebbcba", bold = true }
normal_alt  = { fg = "#ebbcba", bg = "#403d52" }

# Select mode
select_main = { fg = "#191724", bg = "#9ccfd8", bold = true }
select_alt  = { fg = "#9ccfd8", bg = "#403d52" }

# Unset mode
unset_main = { fg = "#191724", bg = "#c4a7e7", bold = true }
unset_alt  = { fg = "#c4a7e7", bg = "#403d52" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#6e6a86" }
perm_type  = { fg = "#ebbcba" }
perm_read  = { fg = "#c4a7e7" }
perm_write = { fg = "#eb6f92" }
perm_exec  = { fg = "#31748f" }

# Progress
progress_label  = { fg = "#c4a7e7", bold = true }
progress_normal = { fg = "#ebbcba", bg = "#403d52" }
progress_error  = { fg = "#eb6f92", bg = "#403d52" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#ebbcba" }
active   = { fg = "#f6c177", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#ebbcba" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#ebbcba" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#ebbcba" }
title   = {}
hovered = { fg = "#f6c177", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#403d52" }
cand            = { fg = "#9ccfd8" }
rest            = { fg = "#6e6a86" }
desc            = { fg = "#f6c177" }
separator       = "  "
separator_style = { fg = "#524f67" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#9ccfd8" }
run     = { fg = "#f6c177" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#403d52", bg = "#e0def4" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#31748f" }
title_warn  = { fg = "#c4a7e7" }
title_error = { fg = "#eb6f92" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#9ccfd8" },

	# Media
	{ mime = "{audio,video}/*", fg = "#c4a7e7" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f6c177" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#31748f" },

	# Fallback
	{ name = "*", fg = "#e0def4" },
	{ name = "*/", fg = "#ebbcba" }
]

# : }}}
